#!/bin/sh
npm run stats
git add ./src/data/code_output.yml     

export git_commits="100"
export git_dates="10/12"
export git_message="test"

cd src/data 

echo -e "\nGenerating git stats file"

# Generate the file
cat > git_stats.yml <<EOL
git-data:
  commits: ${git_commits}
  dates: ${git_dates}
  message: ${git_message}

EOL

cd ../..

exit 0